name: Build and Upload APKs

on:
  push:
    branches:
      - master
    paths:
      - '.github/edit2MakeNewOverlays'

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Installing aapt, zipalign and apksigner
        run: |
          sudo apt-get update
          sudo apt-get install aapt
          sudo apt-get install zipalign
          sudo apt-get install apksigner
      
      - name: Build overlay APKs
        run: |
          rm -rf APKs
          mkdir -p APKs
        
          framework=".github/system/framework/framework-res.apk"
          systemui=".github/system/system_ext/priv-app/SystemUIGoogle/SystemUIGoogle.apk"
          
          for folder in *; do
            if [ -f "$folder/AndroidManifest.xml" ] && [ -d "$folder/res" ]; then
              # Manifest and res directory exist, proceed with building APK
              echo "Building APK for $folder"
              
              # Adjust the build command as per your build system and requirements
              aapt p -f -M "$folder"/AndroidManifest.xml -I $framework -S "$folder"/res -I $systemui -F APKs/"$folder".apk >/dev/null
            else
              # Manifest or res directory is missing, skip building APK
              echo "Skipping $folder (missing manifest or res)"
            fi
          done

      - name: Upload overlay APKs
        uses: actions/upload-artifact@v3
        with:
          name: "AOSPModsOverlays"
          path: .github/Output/*
          if-no-files-found: error
